{
 "title": "BeanMeApp dashboard v1",
 "description": "Testing chart types",
 "time": { "from": "2021-08-24T21:30:00.000Z", "to": "2021-08-25T21:30:00.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"margin:0;padding:0;font-size:42px\"\">Revenue</h1>"
   }
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT SUM(total_spend) FROM delon16.transactions LIMIT 50 "
    }
   ]
  },
  {
   "title": "Revenue by Location (%)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "WITH location_revenues AS (\r\n    SELECT \r\n        l.id AS location_id,\r\n        l.town,\r\n        SUM(t.total_spend) AS revenue\r\n    FROM transactions t\r\n    JOIN locations l ON t.location_id = l.id\r\n    WHERE t.location_id IS NOT NULL\r\n    GROUP BY t.location_id\r\n)\r\nSELECT \r\n    lr.town,\r\n    ROUND((lr.revenue / SUM(lr.revenue) OVER()) * 100, 0) AS percentage_of_total\r\nFROM location_revenues lr;\r\n"
    }
   ]
  },
  {
   "title": "Revenue by Location (UKP) ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "WITH location_revenues AS (\r\n    SELECT \r\n        l.id AS location_id,\r\n        l.town,\r\n        SUM(t.total_spend) AS revenue\r\n    FROM transactions t\r\n    JOIN locations l ON t.location_id = l.id\r\n    WHERE t.location_id IS NOT NULL\r\n    GROUP BY t.location_id\r\n)\r\nSELECT \r\n    lr.town,\r\n    ROUND(lr.revenue, 2) AS revenue_rounded\r\nFROM location_revenues lr ORDER BY lr.revenue DESC;\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"margin:0;padding:0;font-size:42px\"\">Sales</h1>"
   }
  },
  {
   "title": "Sales over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT \r\n  time, \r\n  total_spend \r\nFROM transactions \r\n"
    }
   ]
  },
  {
   "title": "Sales in Product size (%)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    SUM(CASE WHEN size = 'Regular' THEN 1 ELSE 0 END) AS Regular,\r\n    SUM(CASE WHEN size = 'Large' THEN 1 ELSE 0 END) AS Large\r\nFROM baskets\r\nJOIN products ON baskets.product_id = products.id;"
    }
   ]
  },
  {
   "title": "Overall Sales by Product (units)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT \r\n  p.name AS product, \r\n  COUNT(*) AS quantity \r\nFROM baskets b JOIN products p ON b.product_id = p.id \r\nGROUP BY p.name \r\nORDER BY quantity DESC;"
    },
    { "dataset": "delon16" }
   ]
  },
  {
   "title": "Sales of Flavoured coffee (units)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 19 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    p.flavour AS Flavour, \r\n    COUNT(*)  AS Units\r\nFROM baskets b \r\nJOIN products p ON b.product_id = p.id\r\nWHERE p.name IN ('Flavoured iced latte', 'Flavoured latte') \r\nGROUP BY p.flavour \r\nORDER BY Units DESC;"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 19 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    p.flavour AS Flavour, \r\n    COUNT(*)  AS Units\r\nFROM baskets b \r\nJOIN products p ON b.product_id = p.id\r\nWHERE p.name IN ('Flavoured iced latte', 'Flavoured latte') \r\nGROUP BY p.flavour \r\nORDER BY Units DESC;"
    }
   ]
  },
  {
   "title": "Sales of Speciality Teas (units)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 25 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT  \r\n    p.flavour AS Flavour,\r\n    COUNT(b.id) AS Units \r\nFROM \r\n    baskets b \r\nJOIN \r\n    products p ON b.product_id = p.id \r\nWHERE \r\n    p.name = 'Speciality Tea'  \r\nGROUP BY \r\n    p.flavour \r\nORDER BY \r\n    Units DESC;\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT  \r\n    p.flavour AS Flavour,\r\n    COUNT(b.id) AS Units \r\nFROM \r\n    baskets b \r\nJOIN \r\n    products p ON b.product_id = p.id \r\nWHERE \r\n    p.name = 'Speciality Tea'  \r\nGROUP BY \r\n    p.flavour \r\nORDER BY \r\n    Units DESC;\r\n"
    }
   ]
  },
  {
   "title": "Total Sales by Location (units) ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT \r\n  locations.town, \r\n  COUNT(*) AS Units \r\nFROM baskets join transactions on baskets.transaction_id   = transactions.id \r\n             join locations    on transactions.location_id = locations.id \r\nGROUP BY locations.town \r\nORDER BY Units DESC;"
    }
   ]
  },
  {
   "title": "Flavoured iced latte Sales by Size (%)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 31 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    p.flavour AS Flavour,\r\n    SUM(CASE WHEN p.size = 'Regular' THEN 1 ELSE 0 END) AS Regular,\r\n    SUM(CASE WHEN p.size = 'Large'   THEN 1 ELSE 0 END) AS Large\r\nFROM baskets b\r\nJOIN products p ON b.product_id = p.id\r\nWHERE p.name = 'Flavoured iced latte'\r\nGROUP BY p.flavour\r\nORDER BY Flavour ASC;"
    }
   ]
  },
  {
   "title": "Product sales by unit size (in %)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n  p.name,\r\n  SUM(CASE WHEN p.size = 'Large' THEN CAST(p.price AS DECIMAL) ELSE 0 END) AS Large,\r\n  SUM(CASE WHEN p.size = 'Regular' THEN CAST(p.price AS DECIMAL) ELSE 0 END) AS Regular\r\nFROM\r\n  baskets b\r\nJOIN\r\n  products p ON b.product_id = p.id\r\nGROUP BY\r\n  p.name;\r\n"
    }
   ]
  },
  {
   "title": "Flavoured latte Sales by Size (%)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 37 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    p.flavour AS Flavour,\r\n    SUM(CASE WHEN p.size = 'Regular' THEN 1 ELSE 0 END) AS Regular,\r\n    SUM(CASE WHEN p.size = 'Large'   THEN 1 ELSE 0 END) AS Large\r\nFROM baskets b\r\nJOIN products p ON b.product_id = p.id\r\nWHERE p.name = 'Flavoured latte'\r\nGROUP BY p.flavour\r\nORDER BY Flavour ASC;"
    }
   ]
  },
  {
   "title": "Specialty Tea Sales by Size (%)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 42 },
   "targets": [
    {
     "dataset": "delon16",
     "rawSql": "SELECT\r\n    p.flavour AS Flavour,\r\n    SUM(CASE WHEN p.size = 'Regular' THEN 1 ELSE 0 END) AS Regular,\r\n    SUM(CASE WHEN p.size = 'Large'   THEN 1 ELSE 0 END) AS Large\r\nFROM baskets b\r\nJOIN products p ON b.product_id = p.id\r\nWHERE p.name = 'Speciality Tea'\r\nGROUP BY p.flavour\r\nORDER BY Flavour ASC;"
    }
   ]
  }
 ]
}