apiVersion: 1
datasources:
  - name: SuperCafe
    type: postgres
    access: proxy
    url: db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      timeField: transaction_timestamp